print("Enter a noun : ")
noun = input()
print("Enter a verb : ")
verb = input()
print("Enter an adjective : ")
adjective = input()
print("Ente an adverb : ")
adverb = input()
print("Do you "+verb+" your "+adjective+" "+noun+" "+adverb+"?")